# Generated by Django 5.0.6 on 2024-06-02 22:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50, verbose_name='Competition Name')),
                ('location', models.CharField(max_length=150, verbose_name='Competition Location')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RelayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(default=datetime.date(2010, 1, 1), verbose_name='Date Of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=50, verbose_name='Distance')),
                ('strokeType', models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type')),
                ('age_range_lower', models.PositiveSmallIntegerField(default=12, verbose_name='Lower Age Range')),
                ('age_range_upper', models.PositiveSmallIntegerField(default=15, verbose_name='Upper Age Range')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competition')),
                ('groups', models.ManyToManyField(to='home.relaygroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=50, verbose_name='Distance')),
                ('strokeType', models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type')),
                ('age_range_lower', models.PositiveSmallIntegerField(default=12, verbose_name='Lower Age Range')),
                ('age_range_upper', models.PositiveSmallIntegerField(default=15, verbose_name='Upper Age Range')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competition')),
                ('swimmers', models.ManyToManyField(to='home.swimmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwimmerInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokeType', models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.relaygroup')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='relaygroup',
            name='group_members',
            field=models.ManyToManyField(through='home.SwimmerInGroup', to='home.swimmer'),
        ),
        migrations.CreateModel(
            name='SwimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=50, verbose_name='Distance')),
                ('strokeType', models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type')),
                ('time', models.IntegerField(default=1, verbose_name='Time')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Recorded')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimmer')),
                ('swim_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimtime')),
            ],
            options={
                'unique_together': {('swimmer', 'swim_time')},
            },
        ),
    ]
