# Generated by Django 4.1.2 on 2022-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimtime',
            name='distance',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='swimtime',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Front Crawl'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke')], default='FC', max_length=20),
        ),
    ]
