# Generated by Django 4.1.2 on 2022-10-24 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_swimtime_distance_swimtime_stroketype'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 24, 20, 30, 10, 97827, tzinfo=datetime.timezone.utc), verbose_name='Date Recorded'),
        ),
    ]
