# Generated by Django 4.1.2 on 2022-10-24 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_swimtime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimtime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Recorded'),
        ),
    ]
