# Generated by Django 4.1.2 on 2022-11-09 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_swimtime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 12, 32, 28, 880085, tzinfo=datetime.timezone.utc)),
        ),
    ]
