# Generated by Django 4.1.2 on 2022-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_swimmer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
    ]
