# Generated by Django 4.1.2 on 2022-11-09 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_swimmer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='dob',
            field=models.DateField(default=datetime.datetime(2010, 1, 1, 0, 0), verbose_name='Date Of Birth'),
        ),
    ]
