# Generated by Django 4.1.2 on 2022-12-08 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_swimtime_distance_alter_swimtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimtime',
            name='time',
            field=models.DurationField(default=datetime.timedelta(seconds=61, microseconds=1000), verbose_name='Time'),
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimtime')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimmer')),
            ],
            options={
                'unique_together': {('swimmer', 'swimTime')},
            },
        ),
    ]
