# Generated by Django 4.1.2 on 2023-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_race_age_range_race_age_range_lower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='age_range_lower',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Lower Age Range'),
        ),
        migrations.AlterField(
            model_name='race',
            name='age_range_upper',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Upper Age Range'),
        ),
        migrations.AlterField(
            model_name='race',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Front Crawl'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'IM')], default='FC', max_length=20, verbose_name='Stroke Type'),
        ),
        migrations.AlterField(
            model_name='swimtime',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Front Crawl'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'IM')], default='FC', max_length=20, verbose_name='Stroke Type'),
        ),
    ]
