# Generated by Django 4.1.2 on 2023-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_race_age_range_lower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Front Crawl'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type'),
        ),
        migrations.AlterField(
            model_name='swimtime',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Front Crawl'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type'),
        ),
    ]
