# Generated by Django 4.1.2 on 2023-01-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_race_isrelay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='isRelay',
            new_name='is_relay',
        ),
    ]
