# Generated by Django 4.1.2 on 2023-08-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_isrelay_race_is_relay'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='is_relay',
        ),
        migrations.AlterField(
            model_name='race',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type'),
        ),
        migrations.AlterField(
            model_name='swimtime',
            name='strokeType',
            field=models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type'),
        ),
        migrations.CreateModel(
            name='SwimmerInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokeType', models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.relaygroup')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='relaygroup',
            name='group_members',
            field=models.ManyToManyField(through='home.SwimmerInGroup', to='home.swimmer'),
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=50, verbose_name='Distance')),
                ('strokeType', models.CharField(choices=[('FC', 'Freestyle'), ('BC', 'Back Crawl'), ('BF', 'Butterfly'), ('BS', 'Breaststroke'), ('IM', 'Medley')], default='FC', max_length=20, verbose_name='Stroke Type')),
                ('age_range_lower', models.PositiveSmallIntegerField(default=12, verbose_name='Lower Age Range')),
                ('age_range_upper', models.PositiveSmallIntegerField(default=15, verbose_name='Upper Age Range')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.competition')),
                ('groups', models.ManyToManyField(to='home.relaygroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
